version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    volumes:
      - pgdata:/var/lib/postgresql
  mailpit:
    image: axllent/mailpit
    ports:
      # SMTP
      - '1025:1025'
      # Web UI
      - '8025:8025'
volumes:
  pgdata:
