<script lang="ts">
  import { X } from "@lucide/svelte";
  import { goto } from "$app/navigation";
  import { page } from "$app/state";

  import AddLicenseDialog from "$lib/components/app/add-license-dialog.svelte";
  import AssignUserDialog from "$lib/components/app/assign-user-dialog.svelte";
  import DeleteLicense from "$lib/components/app/delete-license.svelte";
  import LicenseKeyCell from "$lib/components/app/license-key-cell.svelte";
  import PageHeader from "$lib/components/app/page-header.svelte";
  import StatusBadge from "$lib/components/app/status-badge.svelte";
  import MultiCombobox from "$lib/components/multi-combobox.svelte";
  import * as Table from "$lib/components/ui/table";
  import { m } from "$lib/paraglide/messages.js";

  import type { PageData } from "./$types";

  let { data }: { data: PageData } = $props();

  const deleteForms = $derived(Object.fromEntries(data.deleteForms.map((f) => [f.data.licenseId, f])));

  const productOptions = $derived(data.products.map((p) => ({ value: p.id, label: p.name })));
  const userOptions = $derived(data.users.map((u) => ({ value: u.id, label: u.name })));

  // Resolves raw URL param terms (IDs or human-readable names) to valid option IDs.
  // Tries exact ID match first, then case-insensitive label match so that URLs like
  // ?user=Emily+Rodriguez work as well as UUID-based URLs generated by the app.
  function resolveToIds(raw: string | null, options: { value: string; label: string }[]): string[] {
    if (!raw) return [];
    return raw
      .split(",")
      .filter(Boolean)
      .reduce<string[]>((acc, term) => {
        const byId = options.find((o) => o.value === term);
        if (byId) {
          acc.push(byId.value);
          return acc;
        }
        const byLabel = options.find((o) => o.label.toLowerCase() === term.toLowerCase());
        if (byLabel) {
          acc.push(byLabel.value);
          return acc;
        }
        return acc;
      }, []);
  }

  // Dialog open state from URL (?add=1&addProduct=<id or name>)
  const initialDialogOpen = page.url.searchParams.get("add") === "1";
  // svelte-ignore state_referenced_locally
  const initialDialogProduct =
    resolveToIds(
      page.url.searchParams.get("addProduct"),
      data.products.map((p) => ({ value: p.id, label: p.name })),
    )[0] ?? "";

  // Filter state — initialised from URL so the page is bookmarkable / shareable.
  // The one-time snapshot of data is intentional: filters are user-controlled, not server-derived.
  // svelte-ignore state_referenced_locally
  let productFilters = $state<string[]>(
    resolveToIds(
      page.url.searchParams.get("product"),
      data.products.map((p) => ({ value: p.id, label: p.name })),
    ),
  );
  // svelte-ignore state_referenced_locally
  let userFilters = $state<string[]>(
    resolveToIds(
      page.url.searchParams.get("user"),
      data.users.map((u) => ({ value: u.id, label: u.name })),
    ),
  );

  $effect(() => {
    // eslint-disable-next-line svelte/prefer-svelte-reactivity
    const params = new URLSearchParams();
    if (productFilters.length) params.set("product", productFilters.join(","));
    if (userFilters.length) params.set("user", userFilters.join(","));
    // eslint-disable-next-line svelte/no-navigation-without-resolve
    void goto(`?${params.toString()}`, { replaceState: true, noScroll: true, keepFocus: true });
  });

  function clearAllFilters() {
    productFilters = [];
    userFilters = [];
  }

  const activeFilters = $derived([
    ...productFilters.map((id) => ({
      key: `product:${id}`,
      label: `${m.licenses_filters_product_label()}: ${data.products.find((p) => p.id === id)?.name ?? id}`,
      clear: () => {
        productFilters = productFilters.filter((v) => v !== id);
      },
    })),
    ...userFilters.map((id) => ({
      key: `user:${id}`,
      label: `${m.licenses_filters_user_label()}: ${userOptions.find((u) => u.value === id)?.label ?? id}`,
      clear: () => {
        userFilters = userFilters.filter((v) => v !== id);
      },
    })),
  ]);

  const filteredLicenses = $derived(
    data.licenses.filter((lic) => {
      if (productFilters.length > 0 && !productFilters.includes(lic.productId)) return false;
      if (userFilters.length > 0 && !userFilters.some((id) => lic.assignedUsers.some((u) => u.id === id))) return false;
      return true;
    }),
  );

  const totalCount = $derived(filteredLicenses.length);
  const assignedCount = $derived(filteredLicenses.filter((lic) => lic.assignedUsers.length > 0).length);
  const availableCount = $derived(totalCount - assignedCount);

  function licenseTypeLabel(usageVolume: number): string {
    return usageVolume === 1 ? m.licenses_table_type_single() : m.licenses_table_type_volume();
  }

  function assignedUsersLabel(users: { name: string }[]): string {
    if (users.length === 0) return "—";
    const shown = users
      .slice(0, 2)
      .map((u) => u.name)
      .join(", ");
    return users.length > 2 ? `${shown} +${users.length - 2}` : shown;
  }
</script>

<svelte:head>
  <title>{m.licenses_popup_add_meta_title()}</title>
  <meta name="licenses" content={m.meta_description()} />
</svelte:head>

<div class="flex h-full w-full flex-col overflow-hidden">
  <PageHeader title={m.licenses_title()} subtitle={m.licenses_subtitle()}>
    <AddLicenseDialog
      form={data.form}
      products={data.products}
      initialOpen={initialDialogOpen}
      defaultProductId={initialDialogProduct}
    />
  </PageHeader>

  <div class="mx-auto w-full max-w-7xl flex-1 overflow-auto px-4 py-6 sm:px-6">
    <div class="flex flex-col gap-4">
      <!-- Stats cards -->
      <div class="grid grid-cols-3 gap-3 sm:gap-4">
        <div class="rounded-lg border bg-white p-3 sm:p-5">
          <p class="text-xs text-gray-500 sm:text-sm">{m.licenses_stats_total()}</p>
          <p class="mt-1 text-2xl font-bold text-gray-900 sm:text-3xl">{totalCount}</p>
        </div>
        <div class="rounded-lg border bg-white p-3 sm:p-5">
          <p class="text-xs text-gray-500 sm:text-sm">{m.licenses_stats_assigned()}</p>
          <p class="mt-1 text-2xl font-bold text-blue-600 sm:text-3xl">{assignedCount}</p>
        </div>
        <div class="rounded-lg border bg-white p-3 sm:p-5">
          <p class="text-xs text-gray-500 sm:text-sm">{m.licenses_stats_available()}</p>
          <p class="mt-1 text-2xl font-bold text-green-600 sm:text-3xl">{availableCount}</p>
        </div>
      </div>

      <!-- Licenses table -->
      <div class="mb-12 overflow-hidden rounded-lg border bg-white">
        <!-- Filter toolbar -->
        <div class="flex flex-wrap items-center gap-2 px-4 py-3 sm:px-6">
          <MultiCombobox
            bind:values={productFilters}
            options={productOptions}
            placeholder={m.licenses_filters_all_products()}
            class="w-44"
          />
          <MultiCombobox
            bind:values={userFilters}
            options={userOptions}
            placeholder={m.licenses_filters_all_users()}
            class="w-44"
          />
        </div>

        <!-- Active filter chips -->
        {#if activeFilters.length > 0}
          <div class="flex flex-wrap items-center gap-2 px-4 pb-2 sm:px-6">
            {#each activeFilters as filter (filter.key)}
              <button
                type="button"
                onclick={filter.clear}
                class="inline-flex items-center gap-1 rounded-full bg-indigo-50 px-2.5 py-0.5 text-xs font-medium text-indigo-700 transition-colors hover:bg-indigo-100"
              >
                {filter.label}
                <X class="h-3 w-3" />
              </button>
            {/each}
            {#if activeFilters.length > 1}
              <button
                type="button"
                onclick={clearAllFilters}
                class="text-xs text-gray-400 hover:text-gray-600 hover:underline"
              >
                {m.licenses_filters_clear_all()}
              </button>
            {/if}
          </div>
        {/if}

        {#snippet licenseActions(lic: (typeof filteredLicenses)[number])}
          <div class="flex items-center gap-0.5">
            <AssignUserDialog
              licenseId={lic.id}
              productName={lic.productName ?? "—"}
              usageVolume={lic.usageVolume}
              {userOptions}
              assignedUsers={lic.assignedUsers.map((u) => ({ value: u.id, label: u.name }))}
            />
            <DeleteLicense licenseId={lic.id} productName={lic.productName ?? "—"} form={deleteForms[lic.id]} />
          </div>
        {/snippet}

        {#if filteredLicenses.length === 0}
          <!-- Empty state -->
          <div class="flex flex-col items-center gap-3 border-t py-16 text-center">
            <p class="text-sm text-gray-500">{m.licenses_table_no_results()}</p>
            <button type="button" onclick={clearAllFilters} class="text-sm font-medium text-indigo-600 hover:underline">
              {m.licenses_filters_clear_all()}
            </button>
          </div>
        {:else}
          <!-- Mobile card list -->
          <ul class="divide-y border-t sm:hidden">
            {#each filteredLicenses as lic (lic.id)}
              <li class="flex flex-col gap-4 p-4">
                <div class="flex items-start justify-between gap-3">
                  <p class="text-lg leading-tight font-bold text-gray-900">{lic.productName ?? "—"}</p>
                  {#if lic.assignedUsers.length === lic.usageVolume}
                    <StatusBadge variant="secondary">
                      {m.licenses_table_status_assigned()}
                    </StatusBadge>
                  {:else if lic.assignedUsers.length > 0 && lic.assignedUsers.length < lic.usageVolume}
                    <StatusBadge variant="secondary">
                      {m.licenses_table_status_partially_assigned()}
                    </StatusBadge>
                  {:else}
                    <StatusBadge variant="success">
                      {m.licenses_table_status_available()}
                    </StatusBadge>
                  {/if}
                </div>
                <div class="flex flex-col gap-1">
                  <p class="text-xs text-gray-400">{m.licenses_table_key()}</p>
                  <LicenseKeyCell key={lic.key} />
                </div>
                <div class="grid grid-cols-2 gap-x-4">
                  <div class="flex flex-col gap-0.5">
                    <p class="text-xs text-gray-400">{m.licenses_table_assigned_to()}</p>
                    <p class="text-sm text-gray-900">{assignedUsersLabel(lic.assignedUsers)}</p>
                  </div>
                  <div class="flex flex-col gap-0.5">
                    <p class="text-xs text-gray-400">{m.licenses_table_type()}</p>
                    <div>
                      <StatusBadge variant="secondary">
                        {licenseTypeLabel(lic.usageVolume)}
                      </StatusBadge>
                    </div>
                  </div>
                </div>
                <div class="flex justify-end">{@render licenseActions(lic)}</div>
              </li>
            {/each}
          </ul>

          <!-- Desktop table -->
          <div class="hidden border-t sm:block">
            <Table.Root>
              <Table.Header class="bg-slate-50">
                <Table.Row class="[&>th]:text-neutral-500">
                  <Table.Head class="pl-6">{m.licenses_table_product()}</Table.Head>
                  <Table.Head>{m.licenses_table_key()}</Table.Head>
                  <Table.Head>{m.licenses_table_status()}</Table.Head>
                  <Table.Head>{m.licenses_table_assigned_to()}</Table.Head>
                  <Table.Head>{m.licenses_table_type()}</Table.Head>
                  <Table.Head>{m.licenses_table_actions()}</Table.Head>
                </Table.Row>
              </Table.Header>
              <Table.Body>
                {#each filteredLicenses as lic (lic.id)}
                  <Table.Row>
                    <Table.Cell class="py-3 pl-6">
                      <span class="font-semibold text-gray-900">{lic.productName ?? "—"}</span>
                    </Table.Cell>
                    <Table.Cell>
                      <LicenseKeyCell key={lic.key} />
                    </Table.Cell>
                    <Table.Cell>
                      {#if lic.assignedUsers.length === lic.usageVolume}
                        <StatusBadge variant="secondary">
                          {m.licenses_table_status_assigned()}
                        </StatusBadge>
                      {:else if lic.assignedUsers.length > 0 && lic.assignedUsers.length < lic.usageVolume}
                        <StatusBadge variant="secondary">
                          {m.licenses_table_status_partially_assigned()}
                        </StatusBadge>
                      {:else}
                        <StatusBadge variant="success">
                          {m.licenses_table_status_available()}
                        </StatusBadge>
                      {/if}
                    </Table.Cell>
                    <Table.Cell class="text-gray-500">
                      {assignedUsersLabel(lic.assignedUsers)}
                    </Table.Cell>
                    <Table.Cell class="text-gray-500">
                      <StatusBadge variant="secondary">
                        {licenseTypeLabel(lic.usageVolume)}
                      </StatusBadge>
                    </Table.Cell>
                    <Table.Cell class="pr-6">
                      {@render licenseActions(lic)}
                    </Table.Cell>
                  </Table.Row>
                {/each}
              </Table.Body>
            </Table.Root>
          </div>
        {/if}
      </div>
    </div>
  </div>
</div>
